### ISSUE TITLE
Empty generator

### ISSUE THREAD

**Issue by info65** [einTosti/BuildSystem#92] opened 2022-03-28 16:24 UTC
Hi,
I have a problem. When I create a map using the EMPTY button, I have a FLAT platform around the map.

**Server information:**

- Minecraft version: 1.18.2.
- Server version Paper version git-Paper-267 (MC: 1.18.2)
- Plugin version 2.18.4

**Comment by einTosti** [comment] 2022-03-29 08:41
Can replicate, however it seems to be a duplicate of #85

**Comment by einTosti** [comment] 2022-03-29 09:02
Nvm, seems to be an issue with unloaded worlds

**Closed** 2022-03-29 09:11 UTC
Labels: status: accepted, type: bug
